### ISSUE TITLE
TypeError: Cannot assign to read only property 'writeQueueSize' of object '#<TCP>'

### ISSUE THREAD

**Issue by zorgoban** [martin-doyle/node-red-contrib-aedes#34]
Hi!

I'm trying to connect from an ESP32 and send MQTT messages to Node-Red using node-red-contrib-aedes. As soon as the ESP32 tries to connect, either with authentication or none, the Node-Red service crashes with the following error message:

8 Dec 19:43:08 - TypeError: Cannot assign to read only property 'writeQueueSize' of object '#\<TCP\>'
    at _clone (/usr/lib/node_modules/node-red/node_modules/clone/clone.js:162:16)
    at _clone (/usr/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
    at clone (/usr/lib/node_modules/node-red/node_modules/clone/clone.js:202:10)
    at Object.cloneMessage (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:91:17)
    at AedesBrokerNode.Node.send (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:410:61)
    at Aedes.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-aedes/aedes.js:138:12)
    at Aedes.emit (events.js:198:13)

Additional Information:
8 Dec 19:48:23 - [info] Node-RED version: v1.0.6
8 Dec 19:48:23 - [info] Node.js version: v10.21.0
8 Dec 19:48:23 - [info] Linux 5.4.79-v7+ arm LE

Node-Red runs on a Raspberry Pi 3 B

Many Greetings!
Remo

**Comment by zorgoban** [comment]
Additional Information:
8 Dec 19:48:23 - [info] Node-RED version: v1.0.6
8 Dec 19:48:23 - [info] Node.js  version: v10.21.0
8 Dec 19:48:23 - [info] Linux 5.4.79-v7+ arm LE

**Comment by martin-doyle** [comment]
Hi Remo,
could you provide the flow you use, please? What are the MQTT settings for Aedes and ESP32?
Thank you.
Martin

**Comment by zorgoban** [comment]
Hi!

I solved the problem with uninstalling Aedes and installing Mosquitto instead. The flow was just the Aedes node plus a debug node on the output. There was not much configuration. Just a name, username and password. I didn't use any db settings.

Many Greetings!
Remo
