### ISSUE TITLE
Problem Maximum call stack size exceeded

### ISSUE THREAD

**Issue by carflomi** [martin-doyle/node-red-contrib-aedes#72]
Hello.
I am using node-red to implement a MQTT broquer (node-red-contrib-aedes) and node-red its working in a Docker, Everything is working correctly but, I detect the following error

```1 Jun 15:05:59 - [red] Uncaught Exception:
1 Jun 15:05:59 - [error] RangeError: Maximum call stack size exceeded
    at AedesBrokerNode.Node.send (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:369:31)
    at Aedes.<anonymous> (/data/node_modules/node-red-contrib-aedes/aedes.js:319:14)
    at Aedes.emit (node:events:513:28)
    at PublishState.callPublished (/data/node_modules/aedes/aedes.js:255:15)
    at makeCallTwo (/data/node_modules/fastseries/series.js:150:3)
    at MQEmitter.release (/data/node_modules/fastseries/series.js:138:7)
    at MQEmitter.parallel [as _parallel] (/data/node_modules/fastparallel/parallel.js:25:12)
    at MQEmitter._do (/data/node_modules/mqemitter/mqemitter.js:133:8)
    at released (/data/node_modules/mqemitter/mqemitter.js:48:12)
    at MQEmitter.parallel [as _parallel] (/data/node_modules/fastparallel/parallel.js:26:7)
```
I don't get more information only that node-network restarts repeatedly 1 time every hour (more or less).

Please can anyone help me with this error?

**Comment by martin-doyle** [comment]
Could you provide some more information about the environment (OS version, Docker version, Node-RED version)?
Could you also provide in Gist a copy of a sample flow, please? 
I would like to check what the issue is.

**Comment by carflomi** [comment]
I have found the problem
The device that is sending the MQTT messages must have some problem and is sending several hundred messages per second.
This causes the indicated problem.
I can inform you that the reported problem is not reproduced on node-network, on a Windows 11 operating system.
These are the data requested
- Yocto linux 5.4.0-144-generic.
- Docker 23.0.6.
- Node-red 3.0.2
Thanks

**Comment by martin-doyle** [comment]
Thank you for your information.
